# Generated by Django 5.2.1 on 2025-05-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_name',
            new_name='birth_date',
        ),
    ]
